# Generated by Django 2.0.5 on 2018-05-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='tried_times',
            field=models.IntegerField(default=0),
        ),
    ]
