# Generated by Django 2.0.5 on 2018-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180514_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价值，单位分'),
        ),
        migrations.AlterField(
            model_name='bookscategory',
            name='category_type',
            field=models.SmallIntegerField(choices=[(1, '一级类别'), (2, '二级类别'), (3, '三级类别')], help_text='类目级别', verbose_name='类目级别'),
        ),
    ]
