# Generated by Django 2.0.5 on 2018-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180515_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=30, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='bookscategory',
            name='category_type',
            field=models.SmallIntegerField(choices=[(1, '一级类别'), (2, '二级类别'), (3, '三级类别')], verbose_name='类目级别'),
        ),
        migrations.AlterField(
            model_name='bookscategory',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='类别名'),
        ),
    ]
