# Generated by Django 2.0.5 on 2018-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180515_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='desc',
            field=models.CharField(default='', max_length=32, verbose_name='描述'),
        ),
    ]
